---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-service-account
type: kubernetes.io/service-account-token
