---
apiVersion: v1
kind: Secret
metadata:
  name: teamcity
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: teamcity
type: kubernetes.io/service-account-token
