apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamcity
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: tc.{{ .Values.teamcity.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teamcity
                port:
                 number: 8111
    - host: {{ .Values.teamcity.lanHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teamcity
                port:
                  number: 8111
