apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.teamcity.resources.storageSize }}
