apiVersion: v1
kind: Service
metadata:
  name: teamcity
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
    component: teamcity
  ports:
    - name: http
      port: 8111
      targetPort: 8111
