---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cloudflared.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- tpl (.Files.Get "files/cloudflared-config.yaml") . | nindent 4 }}
