---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cloudflared.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "cloudflared.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{ include "cloudflared.labels" . | nindent 8 }}
    spec:
      containers:
      - name: cloudflared
        image: "cloudflare/cloudflared:{{ default .Chart.AppVersion .Values.cloudflaredVersion }}"
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: "0.25"
          requests:
            memory: 128Mi
            cpu: "0.1"
      volumes:
      - name: config
        configMap:
          name: {{ .Chart.Name }}-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: creds
        secret:
          secretName: {{ .Values.tunnel.secretName }}
