tunnel: {{ .Values.tunnel.name }}
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
- hostname: k8s.{{ .Values.domainName }}
  service: https://{{ .Values.k8s.apiServerName }}:6443
  originRequest:
    noTLSVerify: true
- service: http_status:404
