apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432