services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=${LOCALTONET_SERVER_DOMAIN} #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0/24 #optional
    volumes:
      - /opt/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  localtonet:
    build:
      context: .
      dockerfile: localtonet.Dockerfile
    image: localtonet:latest
    network_mode: "service:wireguard"
    command: ["authtoken", "${LOCALTONET_TOKEN}"]
    depends_on:
      - wireguard
    restart: unless-stopped
